CREATE EXTENSION jsonb_deep_merge;
select jsonb_deep_merge('{}'::jsonb, '{}'::jsonb);
select jsonb_deep_merge('{"a": 1}'::jsonb, '{}'::jsonb);
select jsonb_deep_merge('{}'::jsonb, '{"a": 1}'::jsonb);
select jsonb_deep_merge('{"b": 2}'::jsonb, '{"a": 1}'::jsonb);
select jsonb_deep_merge('{"b": 2, "a": 1}'::jsonb, '{"a": "3"}'::jsonb);
select jsonb_deep_merge('{"b": {"c": 2}, "a": 1}'::jsonb, '{"a": {"c": 1}}'::jsonb);
select jsonb_deep_merge('{"b": {"c": 2}}'::jsonb, '{"a": 1}'::jsonb);
select jsonb_deep_merge('{"b": {"c": 2}}'::jsonb, '{"b": {"a": 1}}'::jsonb);
select jsonb_deep_merge('{"a": 1, "b": {"c": 3}}'::jsonb, '{"b": {"d": 4}}'::jsonb);
select jsonb_deep_merge('{"a": {"b": 1, "c": 2}}'::jsonb, '{"a": 23}'::jsonb);
select jsonb_deep_merge('{"a": 23}'::jsonb, '{"a": {"b": 1, "c": 2}}'::jsonb);
select jsonb_deep_merge('{"a": {"c": 23}}'::jsonb, '{"a": {"b": 1, "c": {"d": 2}}}'::jsonb);
select jsonb_deep_merge('{"a": {"b": 1, "c": {"d": 2}}}'::jsonb, '{"a": {"c": 23}}'::jsonb);
select jsonb_deep_merge('{"a": {"b": 1}}', '{"a": {"b": false}}');
select jsonb_deep_merge('{"a" : {"b" : 2, "f" : 2}, "c" : 11}'::jsonb, '{"g" : {"b" : null, "f" : false}}'::jsonb);
select jsonb_deep_merge('{"g" : {"b" : null, "f" : false}}':: jsonb, '{"a": {"b" : 2, "f" : 2}, "c" : 11}'::jsonb);
select jsonb_deep_merge('{"a" : {"b" : 2, "f" : 2}, "c" : 11}'::jsonb, '{"a" : {"b" : null, "f" : false}}'::jsonb);
select jsonb_deep_merge('{"a" : {"b" : null, "f" : false}}'::jsonb, '{"a" : {"b" : 2, "f" : 2}, "c" : 11}'::jsonb);
select jsonb_deep_merge('{"a" : {"b" : 2, "f" : 2}, "c" : 11, "z" : false}'::jsonb, '{"a" : {"b" : null, "f" : false}}'::jsonb);
select jsonb_deep_merge('{"a" : {"b" : null, "f" : false}}'::jsonb, '{"a" : {"b" : 2, "f" : 2}, "c" : 11, "z" : false}'::jsonb);
select jsonb_deep_merge('{"a" : {"b" : 2, "f" : 2}, "c" : 11, "z" : false}'::jsonb, '{"a" : {"b" : null, "d" : false}}'::jsonb);
select jsonb_deep_merge('{"a" : {"b" : null, "d" : false}}'::jsonb, '{"a" : {"b" : 2, "f" : 2}, "c" : 11, "z" : false}'::jsonb);
select jsonb_deep_merge('{"b" : 2, "k" : {"k1" : 1, "k2" : 2}}'::jsonb, '{"b" : null, "d" : false, "k" : {"k1" : null, "k2" : false}}'::jsonb);
select jsonb_deep_merge('{"b" : null, "d" : false, "k" : {"k1" : null, "k2" : false}}'::jsonb, '{"b" : 2, "k" : {"k1" : 1, "k2" : 2}}'::jsonb);
select jsonb_deep_merge('{"a" : {"b" : 2, "k" : {"k1" : 1, "k2" : 2}}}'::jsonb, '{"a" : {"b" : null, "d" : false, "k" : {"k1" : null, "k2" : false}}}'::jsonb);
select jsonb_deep_merge('{"a" : {"b" : null, "d" : false, "k" : {"k1" : null, "k2" : false}}}'::jsonb, '{"a" : {"b" : 2, "k" : {"k1" : 1, "k2" : 2}}}'::jsonb);
select jsonb_deep_merge('{"a" : {"b" : 2, "k" : {"k1" : 1, "k2" : 2}}}'::jsonb, '{"a" : {"b" : null, "d" : 2, "k" : {"k1" : null, "k2" : false}}}'::jsonb);
select jsonb_deep_merge('{"a" : {"b" : null, "d" : 2, "k" : {"k1" : null, "k2" : false}}}'::jsonb, '{"a" : {"b" : 2, "k" : {"k1" : 1, "k2" : 2}}}'::jsonb);
select jsonb_deep_merge('{"a" : {"b" : 2, "k" : {"k1" : 1, "k2" : 2}}}'::jsonb, '{"z" : {"b" : null, "d" : false, "k" : {"k1" : null, "k2" : false}}}'::jsonb);
select jsonb_deep_merge('{"z" : {"b" : null, "d" : false, "k" : {"k1" : null, "k2" : false}}}'::jsonb, '{"a" : {"b" : 2, "k" : {"k1" : 1, "k2" : 2}}}'::jsonb);
select jsonb_deep_merge('{"a" : {"b" : 2, "k" : {"k1" : 1, "k2" : 2, "k3" : 2}}, "c" : 11, "z" : false}'::jsonb, '{"a" : {"b" : null, "d" : false, "k" : {"k1" : null, "k2" : false}}}'::jsonb);
select jsonb_deep_merge('{"a" : {"b" : null, "d" : false, "k" : {"k1" : null, "k2" : false}}}'::jsonb, '{"a" : {"b" : 2, "k" : {"k1" : 1, "k2" : 2, "k3" : 2}}, "c" : 11, "z" : false}'::jsonb);
select jsonb_deep_merge('{"a" : {"b" : 2, "f" : 2, "k" : {"k1" : 1, "k2" : 2}}, "c" : 11, "z" : false}'::jsonb, '{"a" : {"b" : null, "d" : false, "n" : {"m" : {}}, "p" : {"k1" : false, "k2" : null}}}'::jsonb);
select jsonb_deep_merge('{"a" : {"b" : null, "d" : false, "n" : {"m" : {}}, "p" : {"k1" : false, "k2" : null}}}'::jsonb, '{"a" : {"b" : 2, "f" : 2, "k" : {"k1" : 1, "k2" : 2}}, "c" : 11, "z" : false}'::jsonb);
select jsonb_deep_merge('{"a" : {"b" : 2, "f" : 2, "k" : {"k1" : 1, "k2" : 2}}, "c" : 11, "z" : false}'::jsonb, '{"a" : {"b" : null, "d" : false, "p" : {"k1" : 5, "k2" : null, "k3": {"kz1" : 1, "kz2" : null}}}}'::jsonb);
select jsonb_deep_merge('{"a" : {"b" : null, "d" : false, "p" : {"k1" : 5, "k2" : null, "k3": {"kz1" : 1, "kz2" : null}}}}'::jsonb, '{"a" : {"b" : 2, "f" : 2, "k" : {"k1" : 1, "k2" : 2}}, "c" : 11, "z" : false}'::jsonb);
select jsonb_deep_merge('{"a" : {"b" : 2, "k" : {"k1" : 1, "k2" : 2, "l" : {"l1" : 1, "l2" : 2}}}}'::jsonb, '{"a" : {"b" : null, "d" : false, "k" : {"k1" : null, "k2" : false, "l" : {"l1" : null, "l2" : false}}}}'::jsonb);
select jsonb_deep_merge('{"a" : {"b" : null, "d" : false, "k" : {"k1" : null, "k2" : false, "l" : {"l1" : null, "l2" : false}}}}'::jsonb, '{"a" : {"b" : 2, "k" : {"k1" : 1, "k2" : 2, "l" : {"l1" : 1, "l2" : 2}}}}'::jsonb);
select jsonb_deep_merge('{}'::jsonb, '{}'::jsonb, false);
select jsonb_deep_merge('{"a": 1}'::jsonb, '{}'::jsonb, false);
select jsonb_deep_merge('{}'::jsonb, '{"a": 1}'::jsonb, false);
select jsonb_deep_merge('{"b": 2}'::jsonb, '{"a": 1}'::jsonb, false);
select jsonb_deep_merge('{"b": 2, "a": 1}'::jsonb, '{"a": "3"}'::jsonb, false);
select jsonb_deep_merge('{"b": {"c": 2}, "a": 1}'::jsonb, '{"a": {"c": 1}}'::jsonb, false);
select jsonb_deep_merge('{"b": {"c": 2}}'::jsonb, '{"a": 1}'::jsonb, false);
select jsonb_deep_merge('{"b": {"c": 2}}'::jsonb, '{"b": {"a": 1}}'::jsonb, false);
select jsonb_deep_merge('{"a": 1, "b": {"c": 3}}'::jsonb, '{"b": {"d": 4}}'::jsonb, false);
select jsonb_deep_merge('{"a": {"b": 1, "c": 2}}'::jsonb, '{"a": 23}'::jsonb, false);
select jsonb_deep_merge('{"a": 23}'::jsonb, '{"a": {"b": 1, "c": 2}}'::jsonb, false);
select jsonb_deep_merge('{"a": {"c": 23}}'::jsonb, '{"a": {"b": 1, "c": {"d": 2}}}'::jsonb, false);
select jsonb_deep_merge('{"a": {"b": 1, "c": {"d": 2}}}'::jsonb, '{"a": {"c": 23}}'::jsonb, false);
select jsonb_deep_merge('{"a": {"b": 1}}', '{"a": {"b": false}}', false);
select jsonb_deep_merge('{"a" : {"b" : 2, "f" : 2}, "c" : 11}'::jsonb, '{"g" : {"b" : null, "f" : false}}'::jsonb, false);
select jsonb_deep_merge('{"g" : {"b" : null, "f" : false}}':: jsonb, '{"a": {"b" : 2, "f" : 2}, "c" : 11}'::jsonb, false);
select jsonb_deep_merge('{"a" : {"b" : 2, "f" : 2}, "c" : 11}'::jsonb, '{"a" : {"b" : null, "f" : false}}'::jsonb, false);
select jsonb_deep_merge('{"a" : {"b" : null, "f" : false}}'::jsonb, '{"a" : {"b" : 2, "f" : 2}, "c" : 11}'::jsonb, false);
select jsonb_deep_merge('{"a" : {"b" : 2, "f" : 2}, "c" : 11, "z" : false}'::jsonb, '{"a" : {"b" : null, "f" : false}}'::jsonb, false);
select jsonb_deep_merge('{"a" : {"b" : null, "f" : false}}'::jsonb, '{"a" : {"b" : 2, "f" : 2}, "c" : 11, "z" : false}'::jsonb, false);
select jsonb_deep_merge('{"a" : {"b" : 2, "f" : 2}, "c" : 11, "z" : false}'::jsonb, '{"a" : {"b" : null, "d" : false}}'::jsonb, false);
select jsonb_deep_merge('{"a" : {"b" : null, "d" : false}}'::jsonb, '{"a" : {"b" : 2, "f" : 2}, "c" : 11, "z" : false}'::jsonb, false);
select jsonb_deep_merge('{"b" : 2, "k" : {"k1" : 1, "k2" : 2}}'::jsonb, '{"b" : null, "d" : false, "k" : {"k1" : null, "k2" : false}}'::jsonb, false);
select jsonb_deep_merge('{"b" : null, "d" : false, "k" : {"k1" : null, "k2" : false}}'::jsonb, '{"b" : 2, "k" : {"k1" : 1, "k2" : 2}}'::jsonb, false);
select jsonb_deep_merge('{"a" : {"b" : 2, "k" : {"k1" : 1, "k2" : 2}}}'::jsonb, '{"a" : {"b" : null, "d" : false, "k" : {"k1" : null, "k2" : false}}}'::jsonb, false);
select jsonb_deep_merge('{"a" : {"b" : null, "d" : false, "k" : {"k1" : null, "k2" : false}}}'::jsonb, '{"a" : {"b" : 2, "k" : {"k1" : 1, "k2" : 2}}}'::jsonb, false);
select jsonb_deep_merge('{"a" : {"b" : 2, "k" : {"k1" : 1, "k2" : 2}}}'::jsonb, '{"a" : {"b" : null, "d" : 2, "k" : {"k1" : null, "k2" : false}}}'::jsonb, false);
select jsonb_deep_merge('{"a" : {"b" : null, "d" : 2, "k" : {"k1" : null, "k2" : false}}}'::jsonb, '{"a" : {"b" : 2, "k" : {"k1" : 1, "k2" : 2}}}'::jsonb, false);
select jsonb_deep_merge('{"a" : {"b" : 2, "k" : {"k1" : 1, "k2" : 2}}}'::jsonb, '{"z" : {"b" : null, "d" : false, "k" : {"k1" : null, "k2" : false}}}'::jsonb, false);
select jsonb_deep_merge('{"z" : {"b" : null, "d" : false, "k" : {"k1" : null, "k2" : false}}}'::jsonb, '{"a" : {"b" : 2, "k" : {"k1" : 1, "k2" : 2}}}'::jsonb, false);
select jsonb_deep_merge('{"a" : {"b" : 2, "k" : {"k1" : 1, "k2" : 2, "k3" : 2}}, "c" : 11, "z" : false}'::jsonb, '{"a" : {"b" : null, "d" : false, "k" : {"k1" : null, "k2" : false}}}'::jsonb, false);
select jsonb_deep_merge('{"a" : {"b" : null, "d" : false, "k" : {"k1" : null, "k2" : false}}}'::jsonb, '{"a" : {"b" : 2, "k" : {"k1" : 1, "k2" : 2, "k3" : 2}}, "c" : 11, "z" : false}'::jsonb, false);
select jsonb_deep_merge('{"a" : {"b" : 2, "f" : 2, "k" : {"k1" : 1, "k2" : 2}}, "c" : 11, "z" : false}'::jsonb, '{"a" : {"b" : null, "d" : false, "n" : {"m" : {}}, "p" : {"k1" : false, "k2" : null}}}'::jsonb, false);
select jsonb_deep_merge('{"a" : {"b" : null, "d" : false, "n" : {"m" : {}}, "p" : {"k1" : false, "k2" : null}}}'::jsonb, '{"a" : {"b" : 2, "f" : 2, "k" : {"k1" : 1, "k2" : 2}}, "c" : 11, "z" : false}'::jsonb, false);
select jsonb_deep_merge('{"a" : {"b" : 2, "f" : 2, "k" : {"k1" : 1, "k2" : 2}}, "c" : 11, "z" : false}'::jsonb, '{"a" : {"b" : null, "d" : false, "p" : {"k1" : 5, "k2" : null, "k3": {"kz1" : 1, "kz2" : null}}}}'::jsonb, false);
select jsonb_deep_merge('{"a" : {"b" : null, "d" : false, "p" : {"k1" : 5, "k2" : null, "k3": {"kz1" : 1, "kz2" : null}}}}'::jsonb, '{"a" : {"b" : 2, "f" : 2, "k" : {"k1" : 1, "k2" : 2}}, "c" : 11, "z" : false}'::jsonb, false);
select jsonb_deep_merge('{"a" : {"b" : 2, "k" : {"k1" : 1, "k2" : 2, "l" : {"l1" : 1, "l2" : 2}}}}'::jsonb, '{"a" : {"b" : null, "d" : false, "k" : {"k1" : null, "k2" : false, "l" : {"l1" : null, "l2" : false}}}}'::jsonb, false);
select jsonb_deep_merge('{"a" : {"b" : null, "d" : false, "k" : {"k1" : null, "k2" : false, "l" : {"l1" : null, "l2" : false}}}}'::jsonb, '{"a" : {"b" : 2, "k" : {"k1" : 1, "k2" : 2, "l" : {"l1" : 1, "l2" : 2}}}}'::jsonb, false);